# Generated by Django 6.0.5 on 2026-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nmae',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
