# Generated by Django 6.0.5 on 2026-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_name_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.IntegerField(max_length=5),
        ),
    ]
