# Generated by Django 6.0.5 on 2026-06-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='qulification',
            new_name='qualification',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
