# Generated by Django 6.0.5 on 2026-06-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_qulification_teacher_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('short_name', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_student', to='school.teacher'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='enter name is numberic', max_length=20, null=True, verbose_name='Grade Name')),
                ('class_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
                ('subject', models.ManyToManyField(to='school.subject')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
